# Generated by Django 3.0.7 on 2024-01-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_servicedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='description_details',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='home.OurService'),
        ),
    ]
