# Generated by Django 3.0.7 on 2024-01-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactform_contactus_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tiktok',
        ),
    ]
