# Generated by Django 3.0.7 on 2024-01-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20240124_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_no_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
