# Generated by Django 3.0.7 on 2024-01-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20240124_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteShortDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('S', 'Service'), ('Z', 'Zodiac Sign'), ('R', 'Review'), ('C', 'Choose Us')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
