# Generated by Django 3.0.7 on 2024-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_websiteshortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteshortdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
