# Generated by Django 3.0.7 on 2024-01-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
